"""Generate a VAPID keypair for Apex Web Push and print .env lines.

Web Push (the transport behind cross-device proactive notifications) signs each
push with a VAPID keypair. Run this once:

    python scripts/gen_vapid_keys.py >> .env

It emits:
  VAPID_PUBLIC_KEY   — base64url uncompressed P-256 point (the browser's
                       applicationServerKey, served via /api/push/vapid)
  VAPID_PRIVATE_KEY  — base64url raw 32-byte scalar (pywebpush's Vapid.from_string)
  VAPID_SUBJECT      — a mailto: contact required by the push services

Keep the private key secret — it lives only in .env (git-ignored).
"""
from __future__ import annotations

import base64

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec


def _b64u(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode()


def main() -> None:
    priv = ec.generate_private_key(ec.SECP256R1())
    pub = priv.public_key()

    raw_point = pub.public_bytes(
        serialization.Encoding.X962,
        serialization.PublicFormat.UncompressedPoint,
    )  # 65 bytes, 0x04 ‖ X ‖ Y
    scalar = priv.private_numbers().private_value.to_bytes(32, "big")

    print("# --- Apex Web Push (VAPID) — generated by scripts/gen_vapid_keys.py ---")
    print(f"VAPID_PUBLIC_KEY={_b64u(raw_point)}")
    print(f"VAPID_PRIVATE_KEY={_b64u(scalar)}")
    print("VAPID_SUBJECT=mailto:you@example.com")


if __name__ == "__main__":
    main()
